name: topo-tomo
channels:
  - conda-forge
  - astra-toolbox/label/dev
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - dask
  - matplotlib
  - astra-toolbox
  - pyedflib
  - opencv
  - astropy
  - h5py
  - jupyter
  - ipython
  - nbformat
  - ipyvolume
  - bokeh
  - tqdm
  - autopep8
  - pylint
  - jupytext
  - pip
